services:
  postgres:
    image: postgres:16
    container_name: link-tracker-database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-link_tracker}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-link_tracker}"]
      interval: 5s
      timeout: 3s
      retries: 2

  migrator:
    image: migrate/migrate:4
    container_name: migrator
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-link_tracker}?sslmode=${POSTGRES_SSLMODE:-disable}",
        "up"
      ]

  scrapper:
    build:
      context: .
      dockerfile: ./deploy/scrapper.Dockerfile
    container_name: link-tracker-scrapper
    depends_on:
      migrator:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      SCRAPPER_HOST: 0.0.0.0
      BOT_HOST: bot
    ports:
      - "${SCRAPPER_PORT:-8081}:${SCRAPPER_PORT:-8081}"
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: ./deploy/bot.Dockerfile
    container_name: link-tracker-bot
    depends_on:
      scrapper:
        condition: service_started
    env_file:
      - .env
    environment:
      BOT_HOST: 0.0.0.0
      SCRAPPER_HOST: scrapper
    ports:
      - "${BOT_PORT:-8080}:${BOT_PORT:-8080}"
    restart: unless-stopped

volumes:
  postgres_data: